booking/urls.py
from django.urls import path
from booking.views import update_max_num_assistants, bi_registration_switch, ReservationList, \
    CourseDetailDelegator, AssistantReservationList

urlpatterns = [
    path('reservation/<str:slug>/', CourseDetailDelegator.as_view(), name='course_detail'),
    path('max_assistants/', update_max_num_assistants, name='update_max_num_assistants'),
    path('bi_registration_switch/', bi_registration_switch, name='bi_registration_switch'),
    path('reservations/', ReservationList.as_view(), name='student_reservation_list'),
    path('assistant_reservations/', AssistantReservationList.as_view(), name='assistant_reservation_list'),
]

itsBooking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from itsBooking.views import Home, populate_db, LoginView, LogoutView, LandingPageDelegator

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', Home.as_view(), name='home'),
    path('populate/', populate_db, name='populate'),
    path('admin/', admin.site.urls),
    path('booking/', include('booking.urls')),
    path('assignments/', include('assignments.urls')),
    path('communications/', include('communications.urls')),
    path('<str:slug>/', LandingPageDelegator.as_view(), name='course_landing_page'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
import calendar
import hashlib
from datetime import time

from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import User, Group
from django.template.defaultfilters import slugify


class Course(models.Model):
    OPEN_BOOKING_TIME = 8  # hour
    CLOSE_BOOKING_TIME = 18  # hour
    BOOKING_INTERVAL_LENGTH = 2  # hours
    RESERVATION_LENGTH = 15  # minutes
    NUM_DAYS_IN_WORK_WEEK = 5
    NUM_RESERVATIONS_IN_BOOKING_INTERVAL = (BOOKING_INTERVAL_LENGTH * 60) // RESERVATION_LENGTH

    title = models.CharField(
        max_length=50,
        unique=True,
    )
    course_code = models.CharField(
        max_length=10,
        unique=True,
    )
    slug = models.SlugField()
    students = models.ManyToManyField(
        User,
        limit_choices_to={'groups__name': "students"},
        related_name="enrolled_courses",
        blank=True,
    )
    assistants = models.ManyToManyField(
        User,
        limit_choices_to={'groups__name': "assistants"},
        related_name="assisting_courses",
        blank=True,
    )
    course_coordinator = models.OneToOneField(
        User,
        limit_choices_to={'groups__name': "course_coordinators"},
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="supervising_course",
    )

    def __str__(self):
        return self.title

    def _generate_booking_intervals(self):
        """
        generates booking intervals associated with a course. 5 2-hour intervals for every weekday
        """
        for day in range(self.NUM_DAYS_IN_WORK_WEEK):
            for hour in range(self.OPEN_BOOKING_TIME,
                              self.CLOSE_BOOKING_TIME,
                              self.BOOKING_INTERVAL_LENGTH):
                start = time(hour=hour, minute=00)
                end = time(hour=hour + 2, minute=00)
                self.booking_intervals.create(day=day, start=start, end=end)

    def save(self, **kwargs):
        if not self.slug:
            self.slug = slugify(self.course_code)
        super().save(**kwargs)
        if not self.booking_intervals.all():
            self._generate_booking_intervals()


class BookingInterval(models.Model):
    DAY_CHOICES = [(str(i), calendar.day_name[i]) for i in range(0, 5)]

    course = models.ForeignKey(
        Course,
        related_name='booking_intervals',
        on_delete=models.CASCADE,
    )
    day = models.CharField(
        max_length=20,
        choices=DAY_CHOICES,
    )
    start = models.TimeField()
    end = models.TimeField()
    max_available_assistants = models.IntegerField(
        default=0,
        validators=[
            MinValueValidator(0)
        ]
    )
    assistants = models.ManyToManyField(
        User,
        limit_choices_to={'groups__name': "assistants"},
        blank=True,
        related_name='setup_booking_intervals',
    )
    nk = models.CharField(
        max_length=32,
        blank=False,
        unique=True,
        primary_key=True,
    )

    class Meta:
        ordering = [
            '-course', 'day', 'start'
        ]

    def _generate_reservation_intervals(self):
        for i in range(Course.NUM_RESERVATIONS_IN_BOOKING_INTERVAL):
            j = i + 1
            self.reservation_intervals.add(
                ReservationInterval.objects.create(
                    index=i,
                    start=time(hour=self.start.hour + (15 * i) // 60, minute=(15 * i) % 60),
                    end=time(hour=self.start.hour + (15 * j) // 60, minute=(15 * j) % 60),
                    booking_interval=self,
                )
            )

    def save(self, **kwargs):
        if not self.nk:
            self.nk = hashlib.md5(
                f'{self.start}-{self.get_day_display()}-{self.course.course_code}'
                    .encode('utf-8')).hexdigest()
        super().save(**kwargs)
        if not self.reservation_intervals.all():
            self._generate_reservation_intervals()

    def __str__(self):
        return f'{self.course.course_code} {self.get_day_display()} {self.start}-{self.end}'


class ReservationInterval(models.Model):
    booking_interval = models.ForeignKey(
        BookingInterval,
        related_name='reservation_intervals',
        on_delete=models.CASCADE,
    )
    index = models.IntegerField(default=0)
    start = models.TimeField()
    end = models.TimeField()

    class Meta:
        ordering = [
            'booking_interval__day'
        ]


class ReservationConnection(models.Model):
    reservation_interval = models.ForeignKey(
        ReservationInterval,
        on_delete=models.CASCADE,
        related_name='connections',
    )
    student = models.ForeignKey(
        User,
        limit_choices_to={'groups__name': "students"},
        related_name='reservations',
        on_delete=models.CASCADE,
    )
    assistant = models.ForeignKey(
        User,
        limit_choices_to={'groups__name': "assistants"},
        related_name='student_connections',
        on_delete=models.CASCADE,
    )

    def _get_available_assistant(self):
        all_bi_assistants = self.reservation_interval.booking_interval.assistants.all()
        reserved_assistants = User.objects.filter(student_connections__in=self.reservation_interval.connections.all())
        available_assistants = all_bi_assistants.difference(reserved_assistants)  # all assistants minus reserved ones
        assert available_assistants.count() > 0, 'No assistants available for this reservation interval'
        return available_assistants[0]

    def save(self, **kwargs):
        if self.pk is None:  # only runs on object creation
            self.assistant = self._get_available_assistant()
        super().save(**kwargs)

    class Meta:
        ordering = [
            'reservation_interval',  # sort by day
            'reservation_interval__start',  # then sort by start time within the day
        ]

booking/forms.py
from django import forms

from booking.models import ReservationInterval
from itsBooking.templatetags.helpers import get_available_reservation_slots


class ReservationConnectionForm(forms.Form):
    reservation_pk = forms.IntegerField(widget=forms.HiddenInput())

    def clean(self):
        reservation = ReservationInterval.objects.get(pk=self.cleaned_data['reservation_pk'])
        if get_available_reservation_slots(reservation) <= 0:
            raise forms.ValidationError('No assistants available for this reservation interval')

booking/views.py
import calendar
from datetime import time

from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView, ListView, FormView
from django.views.generic.base import View, TemplateView

from booking.forms import ReservationConnectionForm
from booking.models import Course, BookingInterval, ReservationInterval, ReservationConnection
from itsBooking.extensions.mixins import UserInGroupMixin
from itsBooking.templatetags.helpers import name
from itsBooking.views import LoginView

WEEKDAYS = list(calendar.day_name)[0:5]


class TableView(DetailView):
    model = Course
    template_name = 'booking/course_detail.html'


class StudentTable(TableView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['weekdays'] = WEEKDAYS
        intervals = []
        for hour in range(Course.OPEN_BOOKING_TIME, Course.CLOSE_BOOKING_TIME, Course.BOOKING_INTERVAL_LENGTH):
            booking_intervals = BookingInterval.objects.filter(Q(start=time(hour=hour)) & Q(course=self.object))
            interval = {
                'start': time(hour),
                'stop': time(hour + Course.BOOKING_INTERVAL_LENGTH),
                'booking_intervals': booking_intervals,
                'reservation_intervals': [{
                    'start': time(hour=hour + (15 * i) // 60, minute=(15 * i) % 60),
                    'stop': time(hour=hour + (15 * (i + 1)) // 60, minute=(15 * (i + 1)) % 60),
                    'reservations': [r.reservation_intervals.filter(index=i).first() for r in
                                     booking_intervals.prefetch_related('reservation_intervals')],
                }
                    for i in range(Course.NUM_RESERVATIONS_IN_BOOKING_INTERVAL)
                ]
            }
            intervals.append(interval)
        context['intervals'] = intervals
        context['form'] = ReservationConnectionForm()
        return context

    def post(self, request, *args, **kwargs):
        return CreateReservationConnection.as_view()(request, *args, **kwargs)


class AssistantTable(TableView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['weekdays'] = WEEKDAYS
        intervals = []
        for hour in range(Course.OPEN_BOOKING_TIME, Course.CLOSE_BOOKING_TIME, Course.BOOKING_INTERVAL_LENGTH):
            booking_intervals = BookingInterval.objects.filter(Q(start=time(hour=hour)) & Q(course=self.object))
            interval = {
                'start': time(hour),
                'stop': time(hour + Course.BOOKING_INTERVAL_LENGTH),
                'booking_intervals': booking_intervals,
            }
            intervals.append(interval)
        context['intervals'] = intervals
        return context


class CourseCoordinatorTable(StudentTable):
    pass


class CreateReservationConnection(UserInGroupMixin, FormView):
    form_class = ReservationConnectionForm
    template_name = 'booking/reservation_input.html'
    allowed_groups = ('students',)

    def get_success_url(self):
        return reverse('course_detail', kwargs={'slug': self.kwargs['slug']})

    def form_valid(self, form):
        reservation_interval = ReservationInterval.objects.get(pk=form.cleaned_data['reservation_pk'])
        reservation_connection = ReservationConnection.objects.create(
            reservation_interval=reservation_interval, student=self.request.user
        )
        success_message = f'Reservasjon opprettet! Din stud. ass. er {name(reservation_connection.assistant)}'
        messages.success(self.request, success_message)
        return super().form_valid(form)

    def form_invalid(self, form):
        error_message = 'Det oppsto en feil under opprettelsen av din reservajon. Vennligst prøv igjen.'
        messages.error(self.request, error_message)
        return super().form_invalid(form)


class CourseDetailDelegator(View):
    delegator = {
        'students': StudentTable.as_view(),
        'assistants': AssistantTable.as_view(),
        'course_coordinators': CourseCoordinatorTable.as_view(),
    }

    def dispatch(self, request, *args, **kwargs):
        # if user not logged in or not in any groups -> 403, if user is missing groups -> Login page
        if not request.user.is_authenticated or not request.user.groups.all():
            raise PermissionDenied
        request_user_group = self.request.user.groups.first().name
        return self.delegator.get(request_user_group, LoginView.as_view())(request, *args, **kwargs)


def update_max_num_assistants(request):
    nk = request.GET.get('nk', None)
    num = request.GET.get('num', None)
    booking_interval = BookingInterval.objects.get(nk=nk)

    if request.user == booking_interval.course.course_coordinator:
        booking_interval.max_available_assistants = num
        booking_interval.save()
        return HttpResponse('')

    raise PermissionDenied()


def bi_registration_switch(request):
    nk = request.GET.get('nk', None)
    booking_interval = BookingInterval.objects.get(nk=nk)

    if not booking_interval.course.assistants.filter(id=request.user.id).exists():
        raise PermissionDenied()
    if not booking_interval.assistants.filter(id=request.user.id).exists():
        booking_interval.assistants.add(request.user.id)
        registration_available = False
    else:
        booking_interval.assistants.remove(request.user.id)
        registration_available = True
    available_assistants_count = booking_interval.assistants.all().count()
    data = {
        'registration_available': registration_available,
        'available_assistants_count': available_assistants_count,
    }
    return JsonResponse(data)


class ReservationList(UserInGroupMixin, ListView):
    template_name = 'booking/reservation_list.html'
    allowed_groups = ('students',)

    def get_queryset(self):
        return ReservationConnection.objects.filter(student=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context.update({'days': WEEKDAYS})
        return context

    def post(self, request):
        try:
            rc = ReservationConnection.objects.get(pk=request.POST['reservation_connection_pk'])
            if rc.student == self.request.user:
                rc.delete()
                success_message = f'Du er nå meldt av reservasjonen!'
                messages.success(request, success_message)
                return HttpResponseRedirect(request.path)
            else:
                raise PermissionDenied("Fy!")
        except ReservationConnection.DoesNotExist:
            error_message = 'Det oppsto en feil ved avmelding av din reservajon. Vennligst prøv igjen.'
            messages.error(request, error_message)
            return self.get(request)


class AssistantReservationList(UserInGroupMixin, TemplateView):
    template_name = 'booking/assistant_reservation_list.html'
    allowed_groups = ('assistants',)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        bis = BookingInterval.objects.filter(assistants=self.request.user)
        booking_intervals = []
        for booking_interval in bis:
            reservation_intervals = booking_interval.reservation_intervals.all()
            booking_intervals.append(
                {
                    'booking_interval': booking_interval,
                    'reservation_intervals': [
                        {
                            'reservation_interval': reservation_interval,
                            'connection': reservation_interval.connections.filter(assistant=self.request.user).first(),
                        }
                        for reservation_interval in reservation_intervals],

                }
            )
        context.update({
            'booking_intervals': booking_intervals
        })
        return context

booking/templates/booking/assistant_reservation_list.html
{% extends 'itsBooking/base.html' %}
{% load helpers %}
{% block body %}

    <style>
td {font-size: 16px;}
    #header {width: 95%; margin-left: 2%;}
</style>
    <div class = "uk-container uk-container-medium">
            <table class="uk-table uk-table-middle" id="header">
                <thead>
                <tr>
                    <th class="uk-width-small">Emnekode</th>
                    <th class="uk-width-medium">Emne</th>
                    <th class="uk-width-small">Dag</th>
                    <th class="uk-width-small">Tid</th>
                    <th class="uk-width-small">Antall reservasjoner</th>
                </tr>
                </thead>
             </table>
    </div>
    <div class = "uk-container uk-container-medium">
        {% for dict in booking_intervals %}
                <ul uk-accordion>
                    <li>
                        <a class="uk-accordion-title uk-card uk-card-default uk-card-body">
                            <table class="uk-table uk-table-middle">
                                <tr>
                                    <td class="uk-width-small">{{ dict.booking_interval.course.course_code }}</td>
                                    <td class="uk-width-medium">{{ dict.booking_interval.course }}</td>
                                    <td class="uk-width-small">{{ dict.booking_interval.get_day_display|nob_day}}</td>
                                    <td class="uk-width-small">{{ dict.booking_interval.start }} - {{ dict.booking_interval.end }}</td>
                                    <td class="uk-width-small">{{ dict.booking_interval|student_count}}</td>
                                </tr>
                            </table>
                        </a>
                        <div class="uk-accordion-content uk-background-muted">
                            <table class="uk-table uk-table-small uk-table-middle">
                                <thead>
                                    <tr>
                                        <th class="uk-width-small uk-text-right">Kvartersintervall</th>
                                        <th class="uk-width-small">Student</th>
                                    </tr>
                                </thead>
                                {% for dict2 in dict.reservation_intervals %}
                                    <tr>
                                        <td class="uk-width-small uk-text-right">
                                            {{ dict2.reservation_interval.start }} - {{ dict2.reservation_interval.end }}
                                        </td>
                                        <td class="uk-width-small uk-text-emphasis">
                                            {% if dict2.connection %}
                                                {{ dict2.connection.student|name }}
                                            {% else %}
                                                <em>Ingen</em>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </li>
                </ul>
        {% endfor %}
    </div>
{% endblock body %}
<h3 class="uk-heading-bullet">{{ reservation  }}</h3>

booking/templates/booking/course_detail.html
{% extends 'itsBooking/base.html' %}
{% load helpers %}

{% block body %}

    <div class="uk-container uk-container-medium">

        <h2>{{ course.course_code }} - {{ course.title }}</h2>

        {% include 'generic/display_messages.html' %}
        {% include 'generic/display_form_errors.html' %}

        {% if request.user|in_group:'students' %}
            {% include 'booking/reservation_input.html' %}

        {% elif request.user|in_group:'course_coordinators' %}
            <ul class="uk-subnav uk-subnav-pill" uk-switcher>

                <li><a href="#">Sett ant. studasser</a></li>
                <li><a href="#">Oppmeldte studasser</a></li>
                <li><a href="#">Oppmeldte studenter</a></li>
            </ul>

            <ul class="uk-switcher uk-margin">

                <li>{% include 'booking/table/set_studentassistants.html' %}</li>
                <li>{% include 'booking/table/cc_studass_overview.html' %}</li>
                <li>{% include 'booking/table/cc_student_overview.html' %}</li>
            </ul>

        {% elif request.user|in_group:'assistants' %}
            {% include 'booking/table/assistant.html' %}
        {% endif %}
        <br>
    </div>

{% endblock %}

booking/templates/booking/course_grid_box.html
<a class="uk-link-reset" href="{% url 'course_landing_page' slug=course.slug %}">
    <div class="uk-card uk-card-primary uk-text-center uk-card-body uk-card-hover">
        <h4>{{ course.course_code }}</h4>
        <h5 class="uk-margin-remove">{{ course }}</h5>
    </div>
</a>

booking/templates/booking/reservation_input.html
{% extends 'booking/reservation_table.html' %}
{% load helpers %}

{% block table_content %}
{% if user|already_made_reservation:reservation %}
    <button type="button" class="uk-button-danger uk-width-small table_button uk-align-center uk-margin-remove"
            uk-tooltip="{{ reservation|available_slots }}/{{ reservation.booking_interval.assistants.count }} ledige">
        PÅMELDT
    </button>
{% else %}
    <button type="button"
            id="{{ reservation.id }}-
                {{ reservation.booking_interval.get_day_display|nob_day }}-
                {{ reservation.start }}-
                {{ reservation.end }}"
        class="uk-width-small table_button uk-align-center uk-margin-remove
    {% if reservation.booking_interval.max_available_assistants == 0 %}
        uk-button-default"disabled>Stengt
    {% elif reservation|available_slots != 0 %}
        uk-button-primary"uk-toggle="target: #reservation_modal" style="cursor: pointer;" onclick="fill_reservation_form(this)">
            {{ reservation|available_slots }}/{{ reservation.booking_interval.assistants.count }} ledig
    {% else%}
        uk-button-default"disabled>
            0/{{ reservation.booking_interval.assistants.count }} ledig
    {% endif %}
    </button>
{% endif %}

<div id="reservation_modal" uk-modal>
    <div class="uk-modal-dialog">
        <form id="reservation_form" method="post">
            {{ form }}
            {% csrf_token %}
            <button class="uk-modal-close-default" type="button" uk-close></button>
            <div class="uk-modal-header">
                <h2 class="uk-modal-title">Reserver</h2>
            </div>
            <div class="uk-modal-body uk-text-center">
                <p>Er du sikker på at vil reservere tid hos studass for intervallet:</p>
                <h5 id="modal_day"></h5>
                <h5 class="uk-margin-remove-top" id="modal_interval"></h5>
            </div>
            <div class="uk-modal-footer uk-text-right">
                <input class="uk-button uk-button-default uk-modal-close" type="reset" value="Avbryt">
                <input class="uk-button uk-button-primary" type="submit" value="Bekreft">
            </div>
        </form>
    </div>
</div>

{% endblock table_content %}

booking/templates/booking/reservation_list.html
{% extends 'itsBooking/base.html' %}
{% load helpers %}


{% block body %}
    <div class="uk-container uk-container-medium">
        {% include 'generic/display_messages.html'%}
        {% for day in days%}
            <h3 class="uk-heading-bullet">{{ day|nob_day }}</h3>
            <div class="uk-card uk-card-default uk-card-body">
                <table class="uk-table uk-table-middle uk-table-divider">
                    <thead>
                        <tr>
                            <th class="uk-width-small">Tid</th>
                            <th class="uk-width-small">Emnekode</th>
                            <th class="uk-width-medium">Emne</th>
                            <th class="uk-width-medium">Studentassistent</th>
                            <th class="uk-width-small">Avmelding</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for connection in object_list %}
                         {% if day == connection.reservation_interval.booking_interval.get_day_display %}
                            <tr>
                                <td>{{ connection.reservation_interval.start }} - {{ connection.reservation_interval.end }}</td>
                                <td>{{ connection.reservation_interval.booking_interval.course.course_code }}</td>
                                <td>{{ connection.reservation_interval.booking_interval.course }}</td>
                                <td>{{ connection.assistant.get_full_name }}</td>
                                <td>
                                    <form method="POST">
                                         {% csrf_token %}
                                        <input type="number" hidden value="{{ connection.pk }}" id="reservation_connection_pk" name="reservation_connection_pk">
                                        <input type="submit" value="Meld Av" class="uk-button uk-button-danger">
                                    </form>
                                </td>

                            </tr>
                         {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endfor %}
    </div>


{% endblock %}

booking/templates/booking/reservation_table.html
{% load helpers %}

{% block body %}

<style>
tr.reservation_row {display: none;}
tr.booking_interval_row {
    font-size: 1.15em;
}
tr.booking_interval_row:hover {
    background-color: rgba(250, 250, 150, 0.3) !important;
    cursor: pointer;}
button.table_button {height: 30px;}
</style>

<div class="uk-container uk-container-center uk-margin-top uk-margin-large-bottom">
    <table class="uk-table uk-table-striped uk-table-small uk-table-middle">
        <thead>
            <tr>
                <th class="uk-width-small">Time</th>
                {% for day in weekdays %}
                    <th class="uk-text-center uk-width-small">{{ day|nob_day }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for interval in intervals %}
                <tr onclick="reveal_reservations(this.id)" id="{{ interval.start }}" class="booking_interval_row">
                    <td>{{ interval.start }} - {{ interval.stop }}</td>
                    <td colspan="4" class="uk-text-center">
                         VIS MER
                    </td>
                    <td></td>
                </tr>
                {% for reservation_interval in interval.reservation_intervals %}
                    <tr class="reservation_row {{ interval.start }}">
                        <td>
                            {{ reservation_interval.start }} - {{ reservation_interval.stop }}
                        </td>
                        {% for reservation in reservation_interval.reservations %}
                            <td>
                                {% block table_content %}{% endblock table_content%}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
</div>

<script>

function fill_reservation_form(element) {
    let data = element.id.split('-');
    $('#id_reservation_pk')[0].value = data[0];

    $('#modal_day')[0].innerText = data[1];
    $('#modal_interval')[0].innerText = data[2] + " - " + data[3];
}

function reveal_reservations(id) {

    // get row that was clicked on
    let parent_row = document.getElementById(id);

    // show every container row
    let all_booking_interval_rows = document.getElementsByClassName("booking_interval_row");
    for (let elt of all_booking_interval_rows) {
        if (elt != parent_row) {
            elt.childNodes[3].innerText = 'VIS MER';
        } else {
            console.log(elt)
        }
    }

    // hide every reservation row
    let all_reservation_rows = document.getElementsByClassName("reservation_row");
    for (let elt of all_reservation_rows) {
        elt.style.display = 'none';
    }

    // Show child (reservation) rows of row clicked, change parent row middle td text
    if (parent_row.innerText.includes('VIS MER')) {

        parent_row.childNodes[3].innerHTML = '<span uk-icon="arrow-up"></span>' +
            ' VIS MINDRE ' +
            '<span uk-icon="arrow-up"></span>';

        let show_reservation_rows = document.getElementsByClassName("reservation_row " + id);
        for (let elt of show_reservation_rows) {
            elt.style.display = 'table-row';
        }
    } else {
        parent_row.childNodes[3].innerText = 'VIS MER';
    }
}

</script>

{% endblock body %}