booking/urls.py
from django.urls import path
from booking.views import update_max_num_assistants, bi_registration_switch, ReservationList, \
    CourseDetailDelegator, AssistantReservationList

urlpatterns = [
    path('reservation/<str:slug>/', CourseDetailDelegator.as_view(), name='course_detail'),
    path('max_assistants/', update_max_num_assistants, name='update_max_num_assistants'),
    path('bi_registration_switch/', bi_registration_switch, name='bi_registration_switch'),
    path('reservations/', ReservationList.as_view(), name='student_reservation_list'),
    path('assistant_reservations/', AssistantReservationList.as_view(), name='assistant_reservation_list'),
]

communications/urls.py
from django.urls import path
from communications.views import *

urlpatterns = [
    path('<str:slug>/announcements/', AnnouncementListView.as_view(), name='announcements'),
    path('announcement/delete/<int:pk>/', DeleteAnnouncementView.as_view(), name='delete_announcement'),
    path('comment/<int:pk>/', CreateCommentView.as_view(), name='create_comment'),
    path('<str:slug>/announcement/<int:pk>/', AnnouncementDetailView.as_view(), name='announcement_detail'),
]

itsBooking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from itsBooking.views import Home, populate_db, LoginView, LogoutView, LandingPageDelegator

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', Home.as_view(), name='home'),
    path('populate/', populate_db, name='populate'),
    path('admin/', admin.site.urls),
    path('booking/', include('booking.urls')),
    path('assignments/', include('assignments.urls')),
    path('communications/', include('communications.urls')),
    path('<str:slug>/', LandingPageDelegator.as_view(), name='course_landing_page'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communications/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from booking.models import Course


def get_avatar_image_path(instance, filename):
    return f'avatars/user_{instance.user.username}_{instance.user.id}/{filename}'


class Announcement(models.Model):
    title = models.CharField(
        max_length=45
    )
    content = models.TextField(
        max_length=1500
    )
    author = models.ForeignKey(
        User,
        limit_choices_to={'groups__name': 'course_coordinators'},
        related_name='announcements',
        on_delete=models.CASCADE,
    )
    course = models.ForeignKey(
        Course,
        related_name='announcement',
        on_delete=models.CASCADE,
    )
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        ordering = (
            '-timestamp',
        )


class Comment(models.Model):
    content = models.TextField(
        max_length=500,
        verbose_name='Kommentar'
    )
    author = models.ForeignKey(
        User,
        limit_choices_to={'groups__name': 'course_coordinators'},
        related_name='comments',
        on_delete=models.CASCADE,
    )
    announcement = models.ForeignKey(
        Announcement,
        related_name='comments',
        on_delete=models.CASCADE,
    )
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('announcement_detail',
                       kwargs={'pk': self.announcement.pk, 'slug': self.announcement.course.slug})


class Avatar(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    image = models.ImageField(
        blank=True,
        upload_to=get_avatar_image_path,
    )

communications/forms.py
from django import forms

from .models import Announcement


class AnnouncementForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'uk-form uk-textarea uk-form-small'
        self.fields['content'].widget.attrs['class'] = 'uk-form uk-textarea uk-form-small'

    class Meta:
        model = Announcement
        fields = ('title', 'content',)

communications/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, ListView, DeleteView, DetailView

from booking.models import Course
from communications.models import Announcement, Comment
from itsBooking.extensions.mixins import UserInGroupMixin
from itsBooking.templatetags.helpers import user_in_group
from .forms import AnnouncementForm


class AnnouncementListView(UserInGroupMixin, ListView):
    model = Announcement
    allowed_groups = ('assistants', 'course_coordinators')

    def get_queryset(self):
        course = get_object_or_404(Course, slug=self.kwargs['slug'])
        return Announcement.objects.filter(course=course).order_by('-id')

    def get_context_data(self):
        context = super().get_context_data()
        if user_in_group(self.request.user, "course_coordinators"):
            context.update({
                'announcement_form': AnnouncementForm(),
            })
        context.update({
            'course': get_object_or_404(Course, slug=self.kwargs['slug'])
        })
        return context

    def post(self, request, *args, **kwargs):
        # handle reviews through a separate view
        return CreateAnnouncementView.as_view()(request, *args, **kwargs)


class AnnouncementDetailView(UserInGroupMixin, DetailView):
    model = Announcement
    allowed_groups = ('assistants', 'course_coordinators')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context.update({
            'comment_form': CreateCommentView.as_view()(self.request).context_data['form']
        })
        context.update({
            'show_delete': True
        })
        return context


class CreateAnnouncementView(UserInGroupMixin, CreateView):
    template_name = 'communications/announcement_list.html'
    model = Announcement
    form_class = AnnouncementForm
    allowed_groups = ('course_coordinators',)

    def get_success_url(self):
        return HttpResponseRedirect(
            reverse('announcements', kwargs={'slug': self.kwargs['slug']})
        )

    def form_valid(self, form):
        announcement = form.save(commit=False)
        announcement.author = self.request.user
        announcement.course = get_object_or_404(
            Course,
            slug=self.kwargs['slug']
        )
        announcement.save()
        return self.get_success_url()


class CreateCommentView(UserInGroupMixin, CreateView):
    model = Comment
    fields = ('content',)
    allowed_groups = ('assistants', 'course_coordinators')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['content'].widget.attrs['class'] = 'uk-textarea uk-form-small'
        form.fields['content'].widget.attrs['placeholder'] = 'Skriv inn din kommentar her...'
        return form

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.announcement = get_object_or_404(Announcement, pk=self.kwargs['pk'])
        comment.save()
        return HttpResponseRedirect(comment.get_absolute_url())


class DeleteAnnouncementView(UserPassesTestMixin, DeleteView):
    model = Announcement

    def test_func(self):
        return self.request.user == self.get_object().course.course_coordinator

    def get_success_url(self):
        announcement = get_object_or_404(Announcement, pk=self.kwargs['pk'])
        return reverse('announcements', kwargs={'slug': announcement.course.slug})

communications/templates/communications/announcement_card.html
{% load static %}

<article class="uk-comment">
    <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
        <div class="uk-width-auto">
            {% include 'generic/display_avatar_img.html' with user=announcement.author %}
        </div>
        <div class="uk-width-expand">
            <h4 class="uk-comment-title uk-margin-remove">
                <a href="{% url 'announcement_detail' slug=announcement.course.slug pk=announcement.pk %}" class="uk-link-text">
                    {{ announcement.title }}
                </a>
            </h4>
            {% url 'announcement_detail' slug=announcement.course.slug pk=announcement.pk as announcement_detail %}
            {% if request.path == announcement_detail %}
            <a href="{% url 'announcements' slug=announcement.course.slug %}" class="uk-align-right">Tilbake</a>
            {% endif %}

            <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                <li>
                    <span uk-icon="icon: user"></span>
                    {{ announcement.author.get_full_name }}</li>
                <li>
                    <span uk-icon="icon: calendar"></span>
                    {{ announcement.timestamp }}
                </li>
                <li><a href="{% url 'announcement_detail' slug=announcement.course.slug pk=announcement.pk %}#comment-container">
                    <span uk-icon="icon: comments"></span>
                    {{ announcement.comments.count }} Kommentarer</a></li>
                <li><a href="{% url 'announcement_detail' slug=announcement.course.slug pk=announcement.pk %}#comment-form">
                    <span uk-icon="icon: reply"></span>
                    Svar</a></li>
                {% if request.user == announcement.author and show_delete %}
                    <li>
                        <button class="uk-button uk-button-small uk-button-default uk-margin-small-right"
                                onclick="set_confirm_delete_modal_action(this)"
                                type="button" uk-toggle="target: #modal-confirm-delete"
                                id="{{ announcement.pk }}">
                            Slett
                        </button>
                    </li>
                {% endif %}
            </ul>
        </div>
    </header>
    <div class="uk-comment-body">
        <p>{{ announcement.content|linebreaks }}</p><br>
    </div>
</article>

communications/templates/communications/announcement_delete_modal.html
<div id="modal-confirm-delete" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
        <h2 class="uk-modal-title">Slett kunngjøring?</h2>
        <p>Er du sikker på at du ønsker å slette denne kunngjøringen og alle tilhørende kommentarer? </p>
        <div class="uk-modal-footer uk-text-right">
            <form method="POST" action="{% url 'delete_announcement' pk=announcement.pk %}" id="confirm-delete-modal-form">
                {% csrf_token %}
                <button class="uk-button uk-button-default uk-modal-close" type="button">Avbryt</button>
                <button class="uk-button uk-button-primary" type="submit">Bekreft</button>
            </form>
        </div>
    </div>
</div>

communications/templates/communications/announcement_detail.html
{% extends 'itsBooking/base.html' %}

{% block body %}
    <div class="uk-container uk-container-small">
        {% include 'communications/announcement_card.html' %}
        <div class="uk-container" id="comment-container">
            {% include 'communications/comment_list.html' %}
        </div>
        <br>
        {% include 'communications/comment_form.html' %}
        <br>
    </div>

    {% include 'communications/announcement_delete_modal.html' %}

    <script>

        function set_confirm_delete_modal_action(elem) {
            let url = "{% url 'delete_announcement' pk=1 %}";
            url = url.split('/').slice(0, -2).join('/') + '/' + elem.id + '/';
            document.getElementById("confirm-delete-modal-form").setAttribute("action", url);
        }

    </script>
{% endblock %}

communications/templates/communications/announcement_form.html
<ul uk-accordion>
    <li class="uk-closed">
        <a class="uk-accordion-title" href="#">Nytt innlegg</a>
        <div class="uk-accordion-content">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="uk-fieldset">
                    {{ announcement_form }}
                    <input type="submit" value="Send" class="uk-button uk-button-primary">
                </fieldset>
            </form>
        </div>
    </li>
</ul>

communications/templates/communications/announcement_list.html
{% extends 'itsBooking/base.html' %}
{% load static %}
{% load helpers %}


{% block body %}
    <div class="uk-container uk-container-small">

        <h2>Kunngjøringer - {{ course.title }}</h2>

        {% if request.user|in_group:"course_coordinators" %}
            {% include 'communications/announcement_form.html' %}
        {% endif %}

        {% for announcement in announcement_list %}
            {% include 'communications/announcement_card.html' %}
            <br>
        {% empty %}
            <p><i>Ingen kunngjøringer</i></p>
        {% endfor %}

    </div>

{% endblock %}

communications/templates/communications/comment_form.html
<form method="POST" action="{% url 'create_comment' pk=announcement.pk %}" id="comment-form">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" value="Send" class="uk-button uk-button-primary uk-align-right">
</form>

communications/templates/communications/comment_list.html
{% for comment in announcement.comments.all %}
    <article class="uk-comment uk-comment-primary">
        <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
            <div class="uk-width-auto">
                {% include 'generic/display_avatar_img.html' with user=comment.author %}
            </div>
            <div class="uk-width-expand">
                <h4 class="uk-comment-title uk-margin-remove">{{ comment.author.get_full_name }}
                    {% if comment.author == comment.announcement.course.course_coordinator %}
                        <span uk-icon="icon: star" style="color: cornflowerblue"></span>
                    {% endif %}
                </h4>
                <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                    <li>{{ comment.timestamp }}</li>
                </ul>
            </div>
        </header>
        <div class="uk-comment-body">
            <p>{{ comment.content }}</p>
        </div>
    </article>
    <hr style="margin: 5px">
{% endfor %}